<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('materials')->insert([
            ['name' => 'Aceite usado', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Acero inoxidable', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Aerosoles, pequeños envases a presión, Extintores sin halones', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Aluminio A', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Aluminio B (DD)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Baterías plomo secas', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cables', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cartón', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chatarra varia (F. Chapajo)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cobre / Aluminio (Radiadores - Cambiadores calor AACC)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cobre tubo', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Componentes electrónicos peligrosos', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Compresores AACC Azules', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Compresores AACC Negros', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Compresores AACC Verdes hierro colado', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Compresores frigoríficos', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Condensadores susceptibles de contener PCBs', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cu / Fe TV (Tarjetas electrónicas pantallas LCDs)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cu / Fe TV (Tarjetas electrónicas pantallas TRCs)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Equipos AACC con CFCs', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Finos', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Fluorescentes', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Frigoríficos con CFCs', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hierro', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hormigón (procedente de A2)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Latón', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Madera', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mezcla residuos generales', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mixte no fèrric', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mixto férrico', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mixto grueso repasado', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Motores eléctricos', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Palets', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Paneles sandwich de LCD', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pilas bastón, alcalinas, NiCd, NiMh, IoLi', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pilas y baterías de litio', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Plástico ABS+PC', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Plástico CDs (Policarbonato)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Plástico difusores pantalla plana', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Plástico frontal Vicor', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Plástico PMMA (metacrilato)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Plástico PP (Polipropileno)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Plástico PS', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Plásticos MIX PAEE', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Polvo aspirado del filtro de mangas', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Polvo electroluminiscente (fosforescente) de TRCs', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Rosetas (yugos deflexión)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tarjetas A', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tarjetas B (RAM)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tarjetas C (PSB)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tarjetas D (Routers / mecanismos)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tarjetas E (Baja calidad)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tarjetas F (Cont)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Telefonos móviles (SM y PDA)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Telefonos moviles no SM', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Termos con espumas con CFCs', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tóner fotocopiadoras no valorizables - D', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tóner para su reutilización', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trafos (cobre/hierro)', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vidrio cono', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vidrio luminarias', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vidrio pantalla TRCs', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vidrio rechazo sin hierro', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zorba', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Zorba férrica', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Deixalleria', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Deixalleria descontaminado', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Deixalleria para triturar', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Industrial', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Industrial descontaminado', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Industrial para triturar', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Luminarias', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Luminarias descontaminado', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Luminarias para triturar', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Recreativas', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Recreativas descontaminadas', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Recreativas para triturar', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Linea blanca para triturar', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE pantalla LED descontaminada', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE pantalla LED para triturar', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE AACC descontaminados', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE AACC para triturar', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Madera descontaminada', 'input' => false, 'output' => true, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'RAEE Madera para triturar', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TRCs Jaula al 25%', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TRCs Jaula al 50%', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TRCs Jaula al 75%', 'input' => true, 'output' => false, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
