<?php

namespace Database\Seeders;

use App\Models\Materials as Material;
use App\Models\Zones as Zone;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ZonesMaterialsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('zones__materials')->insert([
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'Aerosoles, pequeños envases a presión, Extintores sin halones')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'Aluminio B (DD)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'Baterías plomo secas')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'Cables')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'Componentes electrónicos peligrosos')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'Condensadores susceptibles de contener PCBs')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'Madera')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'Mezcla residuos generales')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'Motores eléctricos')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'Pilas bastón, alcalinas, NiCd, NiMh, IoLi')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'Pilas y baterías de litio')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'Plástico CDs (Policarbonato)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'Tarjetas A')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'Tarjetas B (RAM)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'RAEE Deixalleria')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'RAEE Deixalleria descontaminado')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'RAEE Industrial')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'RAEE Industrial descontaminado')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tamesur')->first()->id, 'material_id' => Material::where('name', 'RAEE Madera descontaminada')->first()->id, 'created_at' => now(), 'updated_at' => now()],

            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Acero inoxidable')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Aluminio A')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Aluminio B (DD)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Cables')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Cobre / Aluminio (Radiadores - Cambiadores calor AACC)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Cobre tubo')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Componentes electrónicos peligrosos')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Finos')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Hierro')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Hormigón (procedente de A2)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Latón')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Madera')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Mezcla residuos generales')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Mixte no fèrric')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Mixto férrico')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Mixto grueso repasado')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Motores eléctricos')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Pilas bastón, alcalinas, NiCd, NiMh, IoLi')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Pilas y baterías de litio')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Plásticos MIX PAEE')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Polvo aspirado del filtro de mangas')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Tarjetas A')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Tarjetas E (Baja calidad)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Trafos (cobre/hierro)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Zorba')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'Zorba férrica')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'RAEE Deixalleria para triturar')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'RAEE Industrial para triturar')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'RAEE Luminarias para triturar')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'RAEE Recreativas para triturar')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'RAEE Linea blanca para triturar')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'RAEE pantalla LED para triturar')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'RAEE AACC para triturar')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'MEWA')->first()->id, 'material_id' => Material::where('name', 'RAEE Madera para triturar')->first()->id, 'created_at' => now(), 'updated_at' => now()],

            ['zone_id' => Zone::where('name', 'Vicor')->first()->id, 'material_id' => Material::where('name', 'Cables')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Vicor')->first()->id, 'material_id' => Material::where('name', 'Cu / Fe TV (Tarjetas electrónicas pantallas TRCs)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Vicor')->first()->id, 'material_id' => Material::where('name', 'Hierro')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Vicor')->first()->id, 'material_id' => Material::where('name', 'Mezcla residuos generales')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Vicor')->first()->id, 'material_id' => Material::where('name', 'Plástico ABS+PC')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Vicor')->first()->id, 'material_id' => Material::where('name', 'Plástico frontal Vicor')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Vicor')->first()->id, 'material_id' => Material::where('name', 'Plástico PP (Polipropileno)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Vicor')->first()->id, 'material_id' => Material::where('name', 'Plástico PS')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Vicor')->first()->id, 'material_id' => Material::where('name', 'Polvo electroluminiscente (fosforescente) de TRCs')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Vicor')->first()->id, 'material_id' => Material::where('name', 'Rosetas (yugos deflexión)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Vicor')->first()->id, 'material_id' => Material::where('name', 'Vidrio cono')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Vicor')->first()->id, 'material_id' => Material::where('name', 'Vidrio pantalla TRCs')->first()->id, 'created_at' => now(), 'updated_at' => now()],

            ['zone_id' => Zone::where('name', 'TV planes')->first()->id, 'material_id' => Material::where('name', 'Cu / Fe TV (Tarjetas electrónicas pantallas LCDs)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'TV planes')->first()->id, 'material_id' => Material::where('name', 'Paneles sandwich de LCD')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'TV planes')->first()->id, 'material_id' => Material::where('name', 'Plástico frontal Vicor')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'TV planes')->first()->id, 'material_id' => Material::where('name', 'Plástico PMMA (metacrilato)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'TV planes')->first()->id, 'material_id' => Material::where('name', 'Plástico PP (Polipropileno)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'TV planes')->first()->id, 'material_id' => Material::where('name', 'Plástico PS')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'TV planes')->first()->id, 'material_id' => Material::where('name', 'Plástico difusores pantalla plana')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'TV planes')->first()->id, 'material_id' => Material::where('name', 'Tarjetas A')->first()->id, 'created_at' => now(), 'updated_at' => now()],

            ['zone_id' => Zone::where('name', 'AACC')->first()->id, 'material_id' => Material::where('name', 'Cobre / Aluminio (Radiadores - Cambiadores calor AACC)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'AACC')->first()->id, 'material_id' => Material::where('name', 'Cobre tubo')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'AACC')->first()->id, 'material_id' => Material::where('name', 'Compresores AACC Azules')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'AACC')->first()->id, 'material_id' => Material::where('name', 'Compresores AACC Negros')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'AACC')->first()->id, 'material_id' => Material::where('name', 'Compresores AACC Verdes hierro colado')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'AACC')->first()->id, 'material_id' => Material::where('name', 'Compresores frigoríficos')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'AACC')->first()->id, 'material_id' => Material::where('name', 'Equipos AACC con CFCs')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'AACC')->first()->id, 'material_id' => Material::where('name', 'Frigoríficos con CFCs')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'AACC')->first()->id, 'material_id' => Material::where('name', 'Mezcla residuos generales')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'AACC')->first()->id, 'material_id' => Material::where('name', 'Termos con espumas con CFCs')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'AACC')->first()->id, 'material_id' => Material::where('name', 'RAEE AACC descontaminados')->first()->id, 'created_at' => now(), 'updated_at' => now()],

            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Aceite usado')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Aerosoles, pequeños envases a presión, Extintores sin halones')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Aluminio B (DD)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Baterías plomo secas')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Cables')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Cartón')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Chatarra varia (F. Chapajo)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Componentes electrónicos peligrosos')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Condensadores susceptibles de contener PCBs')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Equipos AACC con CFCs')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Fluorescentes')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Latón')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Madera')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Mezcla residuos generales')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Motores eléctricos')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Palets')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Pilas bastón, alcalinas, NiCd, NiMh, IoLi')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Pilas y baterías de litio')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Plástico CDs (Policarbonato)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Tarjetas A')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Tarjetas B (RAM)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Tarjetas C (PSB)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Tarjetas D (Routers / mecanismos)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Tarjetas E (Baja calidad)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Tarjetas F (Cont)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Telefonos móviles (SM y PDA)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Telefonos moviles no SM')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Termos con espumas con CFCs')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Tóner fotocopiadoras no valorizables - D')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Tóner para su reutilización')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Trafos (cobre/hierro)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Vidrio luminarias')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'Vidrio rechazo sin hierro')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'RAEE Deixalleria')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'RAEE Deixalleria descontaminado')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'RAEE Industrial')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'RAEE Industrial descontaminado')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'RAEE Luminarias')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'RAEE Luminarias descontaminado')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'RAEE Recreativas')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'RAEE Recreativas descontaminadas')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Descontaminació')->first()->id, 'material_id' => Material::where('name', 'RAEE pantalla LED descontaminada')->first()->id, 'created_at' => now(), 'updated_at' => now()],

            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'Cables')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'Mezcla residuos generales')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'Palets')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'Tarjetas A')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'Telefonos móviles (SM y PDA)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'Telefonos moviles no SM')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'Vidrio rechazo sin hierro')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'RAEE Deixalleria')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'RAEE Deixalleria descontaminado')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'RAEE Industrial')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'RAEE Industrial descontaminado')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'RAEE pantalla LED descontaminada')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'RAEE Madera descontaminada')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'TRCs Jaula al 25%')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'TRCs Jaula al 50%')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Tobogan')->first()->id, 'material_id' => Material::where('name', 'TRCs Jaula al 75%')->first()->id, 'created_at' => now(), 'updated_at' => now()],

            ['zone_id' => Zone::where('name', 'Piraña')->first()->id, 'material_id' => Material::where('name', 'Chatarra varia (F. Chapajo)')->first()->id, 'created_at' => now(), 'updated_at' => now()],
            ['zone_id' => Zone::where('name', 'Piraña')->first()->id, 'material_id' => Material::where('name', 'RAEE Industrial')->first()->id, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
